# Generated by Django 4.2.4 on 2023-08-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='assets_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
